### ISSUE TITLE
Exclusively use HTTP POST requests for triggering any actions

### ISSUE THREAD

**Issue by amotl** [ISEMS/ISEMS-ESP32#5]
Hi there,

after just seeing https://github.com/ISEMS/ISEMS-ESP32/commit/933918b6d4499b9ec8e689ac7e0540382aa89b8f#diff-f7a1b4c7fde58e940edb2e8508c9dca3, I suggest using a real HTTP server component [1] instead of

https://github.com/ISEMS/ISEMS-ESP32/blob/933918b6d4499b9ec8e689ac7e0540382aa89b8f/LUA/ff-esp32-openmppt/is.lua#L58-L61

in the long run. Invoking actions based on HTTP GET requests is just too dangerous.

With kind regards,
Andreas.

[1] https://nodemcu.readthedocs.io/en/master/lua-modules/httpserver/

**Comment by elektra42** [comment]
Hi Andreas –
executing commands with HTTP GET and authentication in plain text is not "secure" at all, of course, and the current code is not the final word. I'm currently looking into implementing Digest Access Authentication, as SSL/TLS would cost more resources.

The device is intended to operate as a wireless relay on a hill, for example. The WiFi stack also needs RAM for TX/RX chains, buffers and the available resources are minimal. So I'm looking for preserving RAM.

**Comment by amotl** [comment]
Hello Elektra,

> Executing commands with HTTP GET and authentication in plain text is not "secure" at all.

I hear you regarding cleartext authentication being not secure.

However, triggering actions on a HTTP interface through GET requests is nevertheless a total different kind of story, how ever access protection to this interface might be implemented. Imagine a crawler picking up full qualified links to this interface somewhere or a rogue user agent accidentally invoking such actions.

> The current code is not the final word.

Thanks. We should really consider switching to accepting only POST requests for invoking any actions on the appliance here.

> I'm looking for preserving RAM [for the named reasons].

I see. Do you believe adding and using the HTTP server component [1] will add to RAM usage considerably and so will degrade power efficiency significantly? I see that it might use some additional CPU cycles for properly parsing the HTTP headers and such but on the other hand there will be no need to invoke `string.match(...)` a zillion times in order to check for each actionable option.

So, I believe doing the request processing properly by using a real HTTP implementation will not degrade power efficiency that much compared to the current implementation. However, I will be happy to learn otherwise.

Thanks again and with kind regards,
Andreas.

[1] https://nodemcu.readthedocs.io/en/master/lua-modules/httpserver/

**Comment by amotl** [comment]
Dear Elektra,

after scanning the source code of [httpserver.lua](https://github.com/nodemcu/nodemcu-firmware/blob/3.0-master_20190907/lua_modules/http/httpserver.lua), I found it doesn't even offer an implementation for properly decoding `application/x-www-form-urlencoded` POST request bodies.

An appropriate implementation is available from the `lua-http` library as [`query_args`](https://github.com/daurnimator/lua-http/blob/v0.3/http/util.lua#L50-L70) - an iterator over query segments.

If you feel adding these additional components for having a solid server-side HTTP implementation will drain too much resources energy-wise, feel free to close this issue. My intention just was to bring this up for discussion and keep it here as a reference.

Instead, we might want to focus on #6 and either revisit this afterwards or abandon it completely.

With kind regards,
Andreas.

**Comment by elektra42** [comment]
Hi Andreas - 
thanks. I have added and tested the option to use a one-time sha256 hash of a string containing a public nonce and private key in the mean time. This way the private key is never exposed and it is sufficient to remotely trigger actions on the device (like turning an external load - like a powerful WiFi-mesh-router - on or off) from a script. The entire code with crypto hashing, random key generation libs and the http server code takes ~24 kByte of RAM when active. I consider the level of security sufficient for the application.

Keep your ideas, comments and code coming.

Cheers,
Elektra

**Comment by amotl** [comment]
Dear Elektra,

we are not exactly on the same page here, yet ;]. I recognize there is still a lot of work to do in order to make the appliance ready for general use, so I want to apologize for being so persistent on these details. Probably, this is the wrong time (i.e. too early) to discuss such details, but as you have been kindly answering my thoughts, I feel I can continue trying to add some more of them.

My intention was not to refer to any authentication mechanism to make accessing the appliance somewhat more secure. If this sparked your interest on researching alternative authentication schemes, that's ok ;]. However, this detail focuses on how to transmit credentials over a connection which is insecure by not using any encryption on the transport layer. I do hear you regarding power saving aspects on this matter and why you are reluctant to use TLS in order to save resources.

What I tried to bring up here is that **using HTTP GET requests for invoking any actions is inherently dangerous**, no matter which scheme is used to attach some kind of authentication token to the request payload.

Just imagine any arbitrary intermediary on the HTTP chain is caching your full request, i.e. the complete HTTP URL including its request parameters. This is perfectly valid and allowed for any HTTP proxy servers out there receiving and forwarding GET requests, while it is strictly forbidden for any other HTTP request method like POST, PUT, DELETE, PATCH - you name it. While cache-control mechanisms are embedded within the HTTP protocol through the `Cache-Control` header field, this isn't something I would put any trust onto.

So, regardless of whether we might be using a real Lua HTTP server component to decode the request or not, I want to strongly advise to exclusively use HTTP POST requests for invoking any actions on the device.

All of this is not about protecting against enemy adversaries but more about preventing any accidents from happening by choosing the right protocol details.

Sorry for the noise!

Thanks for listening and with kind regards,
Andreas.

**Comment by elektra42** [comment]
Hi Andreas –

all fine ;) 

The method I'm using is allowing just one command for each key. If anyone wants to cache it - they can be my guest.

Jokes aside, we can talk about implementing it as HTTP POST. I'm based in Berlin and so are you, is that correct? I also wanted to give you a ESP32 developer board (normal NODEMCU) as a gift (so you can run and test the code on your side).

**Comment by amotl** [comment]
Hi Elektra,

> The method I'm using is allowing just one command for each key. If anyone wants to cache it - they can be my guest.

Hmm, I see. But isn't that somehow inconvenient for regular usage and for any automated controlling entity? Sorry to object your idea and corresponding implementation here: While I can assume good intentions, I am dearly and humbly asking you to reconsider this without any offense.

> Jokes aside, we can talk about implementing it as HTTP POST.

See #7, specifically 4c972d5. I was having hard times to rebase this on the latest master and resolve the corresponding merge conflicts - you pushed just three minutes before I had finished this piece. C'est la vie ;].

> I'm based in Berlin and so are you, is that correct? I also wanted to give you a ESP32 developer board (normal NODEMCU) as a gift (so you can run and test the code on your side).

True. That would be awesome! Mind you I am not an electrical engineer at all, so I am humbly asking you for a device I could just plug in and start hacking on it. Do you believe this is feasible?

If you believe I will be able to start hacking the firmware just on the MCU without having a medium- or full-sized ISEMS setup in place, i.e. without the MPPT electronics attached, that would be even cooler and more portable to handle for me. However, I will not be able to conduct larger refactoring of the code base without being able to check I didn't break anything in between then.

Cheers,
Andreas.

**Comment by elektra42** [comment]
Thanks! I have a normal NODEMCU ESP32 board for you at hand. I will solder two resistors to the bottom and the ISEMS firmware will run just fine. All you need is a micro USB cable.
