### ISSUE TITLE
Use MQTT for submitting control commands

### ISSUE THREAD

**Issue by amotl** [ISEMS/ISEMS-ESP32#6]
Hi there,

through #5 ff., I recently became aware of the HTTP-based control interface implemented by these lines within `is.lua`.

https://github.com/ISEMS/ISEMS-ESP32/blob/92b5476f304a6d13d397d3ef1a1c357bdd607405/LUA/ff-esp32-openmppt/is.lua#L58-L96

So, I am humbly asking if you see a point in accessing this control plane also through MQTT in the same spirit as #2?

The big advantage here is that the device does not necessarily has to open a listening socket which has to be reachable from the controlling entity. Instead, it connects to a MQTT broker like before and will be able to receive control commands by subscribing (listening) to a specific MQTT topic.

With kind regards,
Andreas.

**Comment by elektra42** [comment]
Hi Andreas –
thanks for the suggestion! I like the idea.
