### ISSUE TITLE
Standards-based HTTP API

### ISSUE THREAD

**Issue by amotl** [ISEMS/ISEMS-ESP32#8]
Dear Elektra,

thanks for talking about the details of #5 and beyond ;]. My original intention was to standardize some details of the HTTP server implementation in order to improve both usage from within a regular web browser as well as from the command line.

> The device is intended to operate as a wireless relay on a hill, for example. The WiFi stack also needs RAM for TX/RX chains, buffers and the available resources are minimal. So I'm looking for preserving RAM.

Now, I learned that we really have to save memory and have to take care about adding additional libraries - thanks!

On top of that, I learned that people regularly would access the HTTP API from the command line using standard software utilities on (minimal) OpenWRT installations. The tool of choice has been `wget` for [BusyBox](https://www.busybox.net/), so we have to take into consideration which HTTP features this will provide. I hear you.

When adding further changes to the code base, I will take care about any of these details and hope you will still like them.

With kind regards,
Andreas.

**Comment by elektra42** [comment]
With regards to scripting, I have tested the POST method. It works with nc and Telnet. It is not as easy accessible as it was before, though. I have your little present ready :)

**Comment by amotl** [comment]
Dear Elektra,

I've also fiddled with `nc` in order how to bring HTTP Basic Auth into the mix. To keep it as a reference, I am quickly dropping a note about the outcome here.

```
# Define variables.
hostname=my.device.lan
url=/api
username=123
password=456

# Compute authentication header.
auth_header=$(token=$(printf "$username:$password" | base64); printf "Authorization: Basic $token")

# Send request.
printf "GET $url HTTP/1.1\r\nHost:$hostname\r\n$auth_header\r\n\r\n" | nc $hostname 80
```

When adding some more glue code, we could conceive some easy-to-use shell utility out of that solely depending on `sh`/`bash` and `nc`.

With kind regards,
Andreas.

**Comment by elektra42** [comment]
Thanks! That was the idea!

**Comment by amotl** [comment]
Thanks!

The reason why I was hesitating to look further into [HTTP Digest Authentication](https://httpwg.org/specs/rfc7616.html) was that this apparently needs to maintain state on the server side.

If we want to revisit this topic in the future, these are the implementations for Lua I have been able to find on the net:

- https://github.com/pacopink/resty-digest-auth/blob/master/lua/digest_access.lua
- https://github.com/knight42/lua-resty-http-digest/blob/master/lib/resty/http_digest.lua

Apparently, both implementations use [Redis](https://redis.io/) as a database for maintaining state on the server side.

**Comment by amotl** [comment]
> When adding some more glue code, we could conceive some easy-to-use shell utility.

In order to improve on the `nc` side of things, I've just tried to find appropriate resources about how to decode an URL into its components just using bash. Following [1], I am humbly asking you to try these commands within a BusyBox shell (is it actually `bash`?) in order to check if we could actually use that.

```
readonly URI_REGEX='^(([^:/?#]+):)?(//((([^:/?#]+)@)?([^:/?#]+)(:([0-9]+))?))?(/([^?#]*))(\?([^#]*))?(#(.*))?'

parse_host () { [[ "$@" =~ $URI_REGEX ]] && echo "${BASH_REMATCH[7]}"; }
parse_path () { [[ "$@" =~ $URI_REGEX ]] && echo "${BASH_REMATCH[10]}"; }
```

On a vanilla `bash`, it works for me:
```
$ parse_host http://www.example.org/foo/bar
www.example.org

$ parse_path http://www.example.org/foo/bar
/foo/bar
```

Thanks already!

[1] https://stackoverflow.com/questions/6174220/parse-url-in-shell-script/45977232#45977232

**Comment by amotl** [comment]
It looks slicing with `${BASH_REMATCH[7]}` does not work as BusyBox does not have a full-fledged `bash`. Bummer!

**Comment by amotl** [comment]
> When adding some more glue code, we could conceive some easy-to-use shell utility.

[microhttp](https://gist.github.com/amotl/3fd7728b918d2e20e9a07904a7bf7114) is a minimal example solely based on `sed` and `nc`. It kind of works.

It can be invoked like this.
```
microhttp POST http://john:acme@httpbin.org/post "foo=bar&baz=qux"
```
This gives us both HTTP Basic Auth and a standards-based HTTP POST request.

Not having an OpenWRT device at my fingertips, I've tested it using Docker.
```
docker run -v $PWD:/scripts -it --rm busybox ./scripts/microhttp POST http://john:acme@httpbin.org/post "foo=bar&baz=qux"
```

**Comment by amotl** [comment]
A corresponding command based on _GNU Wget 1.20.3_ would be:
```
wget --quiet -X POST http://httpbin.org/post --http-user=john --http-password=acme --auth-no-challenge --post-data="foo=bar&baz=qux" -O-
```

**Comment by amotl** [comment]
BusyBox `wget` apparently will not be able to send HTTP POST requests.
```
/ # wget --help
BusyBox v1.31.1 (2019-12-23 19:20:27 UTC) multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
	[-o|--output-file FILE] [--header 'header: value'] [-Y|--proxy on/off]
	[-P DIR] [-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	--spider	Only check URL existence: $? is 0 if exists
	-c		Continue retrieval of aborted transfer
	-q		Quiet
	-P DIR		Save to DIR (default .)
	-S    		Show server response
	-T SEC		Network read timeout is SEC seconds
	-O FILE		Save to FILE ('-' for stdout)
	-o FILE		Log messages to FILE
	-U STR		Use STR for User-Agent header
	-Y on/off	Use proxy
```

**Comment by elektra42** [comment]
Thanks again for your work, the links and the code. A full blown Digest-Auth according to RFC 7616 is probably overkill.
