### ISSUE TITLE
LoRa option or I2C Interfaxe 

### ISSUE THREAD

**Issue by fafu** [ISEMS/ISEMS-ESP32#9]
Using Lora as a backup even if Wi-Fi is down for status or as a possibility to reset the router would be great. Furthermore, Lora would allow to transmit status data with way less power consumption than Wi-Fi. This could be either achieved by adding Lora capable chips or an easy to use interface as for example I2C to communicate to the ESP32.

**Comment by elektra42** [comment]
The final design has an additional UEXT header that includes I2C, it is already included since prototype version 1.1.
